### PR TITLE
fix: delete datastore

### LINKED ISSUE #2249: Deleting larger datastores with `vsphere_vmfs_datastore` times out
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.8.5

### Terraform Provider

2.8.2

### VMware vSphere

8.0.2.00300

### Description

Possibly related #417 

Deleting vms that have larger disks, In our case 600GBx2, the operation times out since vSphere takes longer than 30s to delete them.

Perhaps having a customizable wait timer would be a good route for this resource, as vSphere seems to be a little iffy on timing.

### Affected Resources or Data Sources

`resources/vsphere_vmfs_datastore`

Possibly this code:

https://github.com/hashicorp/terraform-provider-vsphere/blob/0a41cd630a3c308f789249ddc97f2653c8fd66e2/vsphere/resource_vsphere_vmfs_datastore.go#L407-L415

### Terraform Configuration

```hcl
resource "vsphere_virtual_machine" "pg_db" {
  for_each                = var.pg_db_servers
  name                    = each.key
  annotation              = each.value.annotation
  num_cpus                = each.value.num_cpus
  memory                  = each.value.memory
  folder                  = vsphere_folder.pg_db_folder.path
  datastore_id            = vsphere_vmfs_datastore.pg_data_datastore[each.key].id
  resource_pool_id        = data.terraform_remote_state.core_state.outputs.vsphere_compute_cluster.resource_pool_id
  guest_id                = data.vsphere_virtual_machine.rhel8.guest_id
  scsi_type               = data.vsphere_virtual_machine.rhel8.scsi_type
  tags                    = toset([data.terraform_remote_state.core_state.outputs.rhel_tag.id, data.terraform_remote_state.core_state.outputs.tf_tag.id])
  cpu_hot_add_enabled     = true
  memory_hot_add_enabled  = true
  firmware                = "efi"
  efi_secure_boot_enabled = true

  network_interface {
    network_id = each.value.network_id
  }
  disk {
    label       = "${each.key}.vmdk"
    size        = local.os_volume_size
    unit_number = 0
  }
  disk {
    label       = "${each.key}-data.vmdk"
    size        = each.value.pgdatasize
    unit_number = 1
  }
  disk {
    label        = "${each.key}-pg.vmdk"
    size         = each.value.pgpgsize
    unit_number  = 2
    datastore_id = vsphere_vmfs_datastore.pg_pg_datastore[each.key].id
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.rhel8.id

    customize {
      linux_options {
        host_name = each.key
        domain    = each.value.linux_domain
      }
      dns_server_list = each.value.dns_server_list
      network_interface {
        ipv4_address = each.value.ipv4_address
        ipv4_netmask = each.value.ipv4_netmask
      }
      ipv4_gateway = each.value.ipv4_gateway

    }
  }
  connection {
    type     = "ssh"
    host     = self.default_ip_address
    user     = var.packer_user
    password = var.packer_pass
  }

  lifecycle {
    ignore_changes = [
      disk,
      resource_pool_id,
      clone[0],
      ept_rvi_mode,
      hv_mode
    ]
  }

  depends_on = [
    vsphere_vmfs_datastore.pg_data_datastore,
    vsphere_vmfs_datastore.pg_pg_datastore
  ]

}
```

### Debug Output

https://gist.github.com/ianc769/b6fa08135736fa5db09ff49e5c85bd11

### Panic Output

_No response_

### Expected Behavior

Full Deletion with no issues.

### Actual Behavior

Error Presenting if we hit the 30s mark.

### Steps to Reproduce

Add a VM with a few large disks. Then delete them via Terraform.

### Environment Details

_No response_

### Screenshots

image

### References

#417

### PR DESCRIPTION
**Pull request by mbokman**
### Description

Fixes #2249: Deleting datastores would fail before they were actually deleted, with an error like "Error: could not delete datastore: timeout while waiting for state to become 'retryDeleteCompleted' (timeout: 30s)"

Apologies for not creating an acceptance test but this was my first fix using Go, without knowing Go.

### Acceptance tests

- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```release-note
...
```

### CODE REVIEW

File: vsphere/internal/helper/provider/provider_helper.go [hunk 1]
```diff
@@ -10,7 +10,7 @@ import (
 
 // DefaultAPITimeout is a default timeout value that is passed to functions
 // requiring contexts, and other various waiters.
-const DefaultAPITimeout = time.Minute * 5
+const DefaultAPITimeout = time.Minute * time.Duration(5)
```
Comment (tenthirtyam) [inline vsphere/internal/helper/provider/provider_helper.go:13]: In Go, the most idiomatic way to set a timeout duration using the time package is:

```go
const DefaultAPITimeout = time.Minute * 5
```

Not sure that this change is needed.

File: vsphere/resource_vsphere_vmfs_datastore.go [hunk 2]
```diff
@@ -378,7 +378,7 @@ func resourceVSphereVmfsDatastoreDelete(d *schema.ResourceData, meta interface{}
 		Pending:    []string{retryDeletePending},
 		Target:     []string{retryDeleteCompleted},
 		Refresh:    deleteRetryFunc,
-		Timeout:    30 * time.Second,
+		Timeout:    defaultAPITimeout,
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_vmfs_datastore.go:381]: This `Timeout` is from the `vsphere` package, not the one in the `provider` package also changed in this PR.

`defaultAPITimeout` is not exported in the `vsphere` package and is defined in the most idiomatic way to set a timeout duration using the time package:

```go
var defaultAPITimeout = time.Minute * 5
```

I don't see the need to for the change to `provider.DefaultAPITimeout` however.

File: vsphere/internal/helper/provider/provider_helper.go (hunk 1 above)
Comment (mbokman) [reply vsphere/internal/helper/provider/provider_helper.go:13]: I tried to follow what I thought was being used elsewhere but I will revert.

File: vsphere/resource_vsphere_vmfs_datastore.go (hunk 2 above)
Comment (mbokman) [reply vsphere/resource_vsphere_vmfs_datastore.go:381]: I am a total n00b and I am not getting everything you said but I know this change solved my datastore deletion issue. I hope you will accept it.

**Review by tenthirtyam — APPROVED** [review]
LGTM.

**Review by spacegospod — APPROVED** [review]
LGTM
