### PR TITLE
Avoid nil condition for guestID

### LINKED ISSUE #1229: Error: rpc error: code = Unavailable desc = transport is closing
### Terraform Version
0.12.29

### vSphere Provider Version
terraform-provider-vsphere_v1.24.1_x4.exe

### Affected Resource(s)
`vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
	user = "administrator@vsphere.ncsl"
	password = "redacted"
	vsphere_server = "pxtor-cpvcsa1.corp.ad.ncsl"
	allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
	name = "TOR"
}

data "vsphere_datastore" "datastore" {
	name = "NFS02"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore" "datastore_iso" {
	name = "NFS03_ISO_files"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


data "vsphere_resource_pool" "pool" {
	name = "DEV"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
	name = "VM_APP"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
	name = "RHEL7_192.168.2.201"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

/*
data "vsphere_virtual_machine" "newTfVm" {
	name "newTfVm"
	datacenter_id   = "${data.vsphere_datacenter.dc.id}"
	resourcepool_id = "${data.vsphere_datastore.datastore.id}"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
*/

resource "vsphere_virtual_machine" "newWIN2012R2" {
	name = "WIN2012R2_TF"
	resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
	datastore_id = "data.vsphere_datastore.datastore.id"

	num_cpus = 1
	memory = 2048
	guest_id = "windows8Server64Guest"
	scsi_type = "pvscsi"
	wait_for_guest_net_timeout = 1
	
	network_interface {
		network_id = "data.vsphere_network.network.id"
	}

	disk {
		label = "WIN2012R2_TF.vmdk"
		thin_provisioned = true
		size = 25
	}

	cdrom {
		datastore_id = "data.vsphere_datastore.iso_datastore.id"
		path = "en_windows_server_2012_r2_with_update_x64_dvd_4065220.iso"
	}
}
```

### Debug Output

https://gist.github.com/aenagy/c72710fe5fabbcf391871ff71dd4787e

### Panic Output

https://gist.github.com/aenagy/f2c79b359de66eca377aee2065525d42

### Expected Behavior

terraform should have created new vSphere virtual machine.

### Actual Behavior

terraform did not create new vSphere virtual machine, it crashed.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Important Factoids

(1) WARNING: Terraform newb
(2) Using Terraform 0.12.29 as this is what my client is using.
(3) Running on Windows 10 (1909) with PowerShell (not git bash, etc.)
(4) vSphere 6.7 is running on same machine using VMware Workstation, i.e. traffic does not leave machine. I am able to login to vSphere web GUI. Output from terraform does indicate that is is able to see resources within.
(5) 'terraform apply' without the virtual machine resource didn't produce errors.
(6) Inspired by https://www.youtube.com/watch?v=nQ7oRSi6mBU but that shouldn't matter.

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by bill-rich**
Fixes #1229

### CODE REVIEW

File: vsphere/resource_vsphere_virtual_machine.go [hunk 1]
```diff
@@ -1208,11 +1208,14 @@ func resourceVSphereVirtualMachineCreateBare(d *schema.ResourceData, meta interf
 	// environment info in the resource pool, which we can then filter through
 	// our device CRUD lifecycles to get a full deviceChange attribute for our
 	// configspec.
-	var guestID interface{}
-	if _, ok := d.GetOk("guest_id"); !ok {
+	var guestID string
```
Comment (jrhouston) [inline vsphere/resource_vsphere_virtual_machine.go:1211]: Rather than having an else block to set the default case, what about this:

```
guestID := "other-64"
if guestInterface, ok := d.GetOk("guest_id"); ok {
    guestID = guestInterface.(string)
} 
```

**Review by jrhouston — APPROVED** [review]
Just added a cosmetic suggestion.

File: vsphere/resource_vsphere_virtual_machine.go (hunk 1 above)
Comment (bill-rich) [reply vsphere/resource_vsphere_virtual_machine.go:1211]: Thank you!!! For whatever reason, I could not see that yesterday!
