### PR TITLE
fix: add version check for vsan hci mesh

### LINKED ISSUE #1925: Failed to create a cluster with vSAN enabled on 7.0 vSphere
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.2.1

### Terraform Provider

v2.4.0

### VMware vSphere

v7.0

### Description

When creating a cluster with vSAN enabled on 7.0 vSphere testbed, it's failed with such err msg output to console:
`Error: cannot apply vsan remote datastores on cluster 'test': General vSAN error.`

The RC is that provider configures vSAN remote datastores no matter which version env is. But this feature is supported only on 70U1 or later, ref: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vsan.doc/GUID-9113BBD6-5428-4287-9F61-C8C3EE51E07E.html

### Affected Resources or Data Sources

`vsphere_compute_cluster`

### Terraform Configuration

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_compute_cluster.cluster will be created
  + resource "vsphere_compute_cluster" "cluster" {
      + datacenter_id                                         = "datacenter-3"
      + dpm_automation_level                                  = "manual"
      + dpm_enabled                                           = false
      + dpm_threshold                                         = 3
      + drs_automation_level                                  = "manual"
      + drs_enable_vm_overrides                               = true
      + drs_enabled                                           = false
      + drs_migration_threshold                               = 3
      + drs_scale_descendants_shares                          = "disabled"
      + ha_admission_control_host_failure_tolerance           = 1
      + ha_admission_control_performance_tolerance            = 100
      + ha_admission_control_policy                           = "resourcePercentage"
      + ha_admission_control_resource_percentage_auto_compute = true
      + ha_admission_control_resource_percentage_cpu          = 100
      + ha_admission_control_resource_percentage_memory       = 100
      + ha_admission_control_slot_policy_explicit_cpu         = 32
      + ha_admission_control_slot_policy_explicit_memory      = 100
      + ha_datastore_apd_recovery_action                      = "none"
      + ha_datastore_apd_response                             = "disabled"
      + ha_datastore_apd_response_delay                       = 180
      + ha_datastore_pdl_response                             = "disabled"
      + ha_enabled                                            = false
      + ha_heartbeat_datastore_policy                         = "allFeasibleDsWithUserPreference"
      + ha_host_isolation_response                            = "none"
      + ha_host_monitoring                                    = "enabled"
      + ha_vm_component_protection                            = "enabled"
      + ha_vm_dependency_restart_condition                    = "none"
      + ha_vm_failure_interval                                = 30
      + ha_vm_maximum_failure_window                          = -1
      + ha_vm_maximum_resets                                  = 3
      + ha_vm_minimum_uptime                                  = 120
      + ha_vm_monitoring                                      = "vmMonitoringDisabled"
      + ha_vm_restart_priority                                = "medium"
      + ha_vm_restart_timeout                                 = 600
      + host_cluster_exit_timeout                             = 3600
      + id                                                    = (known after apply)
      + name                                                  = "test"
      + proactive_ha_automation_level                         = "Manual"
      + proactive_ha_moderate_remediation                     = "QuarantineMode"
      + proactive_ha_severe_remediation                       = "QuarantineMode"
      + resource_pool_id                                      = (known after apply)
      + vsan_compression_enabled                              = false
      + vsan_dedup_enabled                                    = false
      + vsan_dit_encryption_enabled                           = false
      + vsan_dit_rekey_interval                               = (known after apply)
      + vsan_enabled                                          = true
      + vsan_network_diagnostic_mode_enabled                  = false
      + vsan_performance_enabled                              = false
      + vsan_stretched_cluster_enabled                        = false
      + vsan_unmap_enabled                                    = false
      + vsan_verbose_mode_enabled                             = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Debug Output

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vsphere_compute_cluster.cluster: Creating...
╷
│ Error: cannot apply vsan remote datastores on cluster 'test': General vSAN error.
│
│   with vsphere_compute_cluster.cluster,
│   on test.tf line 63, in resource "vsphere_compute_cluster" "cluster":
│   63: resource "vsphere_compute_cluster" "cluster" {
```

### Panic Output

_No response_

### Expected Behavior

vSAN enabled cluster is created successfully.

### Actual Behavior

cluster creation failed

### Steps to Reproduce

Edit .tf files as above shows and run terraform apply.

### Environment Details

_No response_

### Screenshots

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by zxinyu08**
### Description

Add version check before handling vSAN HCI Mesh, since this feature is supported in 70U1 or later.

Test Result:

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:
End-to-end test on vSphere 7.0 with only vSAN enabled. Configuration won't be failed anymore.
```
$ terraform apply
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
vsphere_compute_cluster.cluster: Refreshing state... [id=domain-c45]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_compute_cluster.cluster will be created
  + resource "vsphere_compute_cluster" "cluster" {
      + datacenter_id                                         = "datacenter-3"
      + dpm_automation_level                                  = "manual"
      + dpm_enabled                                           = false
      + dpm_threshold                                         = 3
      + drs_automation_level                                  = "manual"
      + drs_enable_vm_overrides                               = true
      + drs_enabled                                           = false
      + drs_migration_threshold                               = 3
      + drs_scale_descendants_shares                          = "disabled"
      + ha_admission_control_host_failure_tolerance           = 1
      + ha_admission_control_performance_tolerance            = 100
      + ha_admission_control_policy                           = "resourcePercentage"
      + ha_admission_control_resource_percentage_auto_compute = true
      + ha_admission_control_resource_percentage_cpu          = 100
      + ha_admission_control_resource_percentage_memory       = 100
      + ha_admission_control_slot_policy_explicit_cpu         = 32
      + ha_admission_control_slot_policy_explicit_memory      = 100
      + ha_datastore_apd_recovery_action                      = "none"
      + ha_datastore_apd_response                             = "disabled"
      + ha_datastore_apd_response_delay                       = 180
      + ha_datastore_pdl_response                             = "disabled"
      + ha_enabled                                            = false
      + ha_heartbeat_datastore_policy                         = "allFeasibleDsWithUserPreference"
      + ha_host_isolation_response                            = "none"
      + ha_host_monitoring                                    = "enabled"
      + ha_vm_component_protection                            = "enabled"
      + ha_vm_dependency_restart_condition                    = "none"
      + ha_vm_failure_interval                                = 30
      + ha_vm_maximum_failure_window                          = -1
      + ha_vm_maximum_resets                                  = 3
      + ha_vm_minimum_uptime                                  = 120
      + ha_vm_monitoring                                      = "vmMonitoringDisabled"
      + ha_vm_restart_priority                                = "medium"
      + ha_vm_restart_timeout                                 = 600
      + host_cluster_exit_timeout                             = 3600
      + id                                                    = (known after apply)
      + name                                                  = "test"
      + proactive_ha_automation_level                         = "Manual"
      + proactive_ha_moderate_remediation                     = "QuarantineMode"
      + proactive_ha_severe_remediation                       = "QuarantineMode"
      + resource_pool_id                                      = (known after apply)
      + vsan_compression_enabled                              = false
      + vsan_dedup_enabled                                    = false
      + vsan_dit_encryption_enabled                           = false
      + vsan_dit_rekey_interval                               = (known after apply)
      + vsan_enabled                                          = true
      + vsan_network_diagnostic_mode_enabled                  = false
      + vsan_performance_enabled                              = false
      + vsan_stretched_cluster_enabled                        = false
      + vsan_unmap_enabled                                    = false
      + vsan_verbose_mode_enabled                             = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vsphere_compute_cluster.cluster: Creating...
vsphere_compute_cluster.cluster: Creation complete after 7s [id=domain-c47]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```markdown
BUG FIXES:

`r/vsphere_compute_cluster`:  Added version check for [vSphere 7.0.1 or later](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vsan.doc/GUID-9113BBD6-5428-4287-9F61-C8C3EE51E07E.html) when enabling vSAN HCI Mesh. ([#1931](https://github.com/terraform-providers/terraform-provider-vsphere/pull/1931))
```
### References

Closes #1925

### CODE REVIEW

**Review by tenthirtyam — APPROVED** [review]
LGTM! :octocat:

File: vsphere/resource_vsphere_compute_cluster.go [hunk 1]
```diff
@@ -1385,14 +1385,16 @@ func resourceVSphereComputeClusterFlattenData(
 		d.Set("vsan_dit_rekey_interval", 0)
 	}
 
-	var dsIDs []string
-	if vsanConfig.DatastoreConfig != nil {
-		for _, ds := range vsanConfig.DatastoreConfig.(*vsantypes.VsanAdvancedDatastoreConfig).RemoteDatastores {
-			dsIDs = append(dsIDs, ds.Value)
+	if version.AtLeast(viapi.VSphereVersion{Product: version.Product, Major: 7, Minor: 1}) {
```
Comment (appilon) [inline vsphere/resource_vsphere_compute_cluster.go:1388]: is vsphere 7.0U1 considered 7.1? or 7.0.1. I believe you need to use the `Patch` field instead of `Minor` if that were the case?

File: vsphere/resource_vsphere_compute_cluster.go [hunk 2]
```diff
@@ -1498,15 +1505,17 @@ func resourceVSphereComputeClusterApplyVsanConfig(d *schema.ResourceData, meta i
...
-	datastoreConfig, err := expandVsanDatastoreConfig(d, meta)
-	if err != nil {
-		return err
-	}
-	if err := vsanclient.Reconfigure(meta.(*Client).vsanClient, cluster.Reference(), vsantypes.VimVsanReconfigSpec{
-		Modify:          true,
-		DatastoreConfig: datastoreConfig,
-	}); err != nil {
-		return fmt.Errorf("cannot apply vsan remote datastores on cluster '%s': %s", d.Get("name").(string), err)
+	if version.AtLeast(viapi.VSphereVersion{Product: version.Product, Major: 7, Minor: 1}) {
```
Comment (appilon) [inline vsphere/resource_vsphere_compute_cluster.go:1508]: same as above

File: vsphere/resource_vsphere_compute_cluster.go (hunk 1 above)
Comment (tenthirtyam) [reply vsphere/resource_vsphere_compute_cluster.go:1388]: Nice catch - it's 7.0.1 and this would look for 7.1.

File: vsphere/resource_vsphere_compute_cluster.go (hunk 2 above)
Comment (tenthirtyam) [reply vsphere/resource_vsphere_compute_cluster.go:1508]: Nice catch - it's 7.0.1 and this would look for 7.1.

File: vsphere/resource_vsphere_compute_cluster.go (hunk 1 above)
Comment (tenthirtyam) [reply vsphere/resource_vsphere_compute_cluster.go:1388]:
```suggestion
	if version.AtLeast(viapi.VSphereVersion{Product: version.Product, Major: 7, Minor: 0, Patch: 1}) {
```

File: vsphere/resource_vsphere_compute_cluster.go (hunk 2 above)
Comment (tenthirtyam) [reply vsphere/resource_vsphere_compute_cluster.go:1508]:
```suggestion
	if version.AtLeast(viapi.VSphereVersion{Product: version.Product, Major: 7, Minor: 0, Patch: 1}) {
```

Comment (tenthirtyam) [reply vsphere/resource_vsphere_compute_cluster.go:1508]: Suggestion above.

File: vsphere/resource_vsphere_compute_cluster.go (hunk 1 above)
Comment (tenthirtyam) [reply vsphere/resource_vsphere_compute_cluster.go:1388]: Suggestion above.

**Comment by zxinyu08** [comment]
Thanks @appilon @tenthirtyam for catching this, just committed changes.

**Review by tenthirtyam — APPROVED** [review]

**Review by appilon — APPROVED** [review]
I cannot easily test this situation but it seems fine. In general I don't like that these version edgecases are littered throughout the provider and sort of "silently fail". I think I'd prefer warnings or errors if a user tries to configure an attribute they don't have support for, but we can continue with precedant.
