### PR TITLE
fix: `r/vsphere_host` thumbprint error

### LINKED ISSUE #1549: `vsphere_host` does not check thumbprint
### Terraform Version

```
# terraform -v
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.0.2
```

### vSphere Provider Version
`+ provider registry.terraform.io/hashicorp/vsphere v2.0.2`
### vSphere Version
`vSphere 7.0 Update 2`

### Affected Resource(s)
`vsphere_host`

### Terraform Configuration Files
```hcl
provider "vsphere" {
  user           = "administrator@vsphere.local"
  password       = "password"
  vsphere_server = "192.168.1.1"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}
data "vsphere_datacenter" "dc" {
  name = "DC1"
}

resource "vsphere_host" "esx1" {
  hostname   = "192.168.1.2"
  username   = "root"
  password   = "password"
#  license    = "00000-00000-00000-00000i-00000"
  datacenter = data.vsphere_datacenter.dc.id
  thumbprint = "AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA"
}

resource "vsphere_host" "esx2" {
  hostname   = "192.168.1.2"
  username   = "root"
  password   = "password"
#  license    = "00000-00000-00000-00000i-00000"
  datacenter = data.vsphere_datacenter.dc.id
  thumbprint = "AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA:AA"
}
```

### Expected Behavior
The hash should be check and I shouldn't be able to import 2 esx with same hash when they have differents certificates. 
### Actual Behavior
I can add multiples esx with the same hash

### Steps to Reproduce
* Create 2 esxi
* Create 1 vCenter (not sur is usefull)
* Run the terraform part above without changing the thumbprint.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### PR DESCRIPTION
**Pull request by burnsjared0415**
### Description

Adds validation of the ESXI host thumbprint before adding the host to a cluster or vCenter Server.

### Acceptance tests

- [ ] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereHost_rootFolder$ github.com/hashicorp/terraform-provider-vsphere/vsphere

ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.900s
```

```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereHost_connection$ github.com/hashicorp/terraform-provider-vsphere/vsphere

ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.907s
```
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereHost_maintenance$ github.com/hashicorp/terraform-provider-vsphere/vsphere

ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.950s
```

### Release Note

`resource/vsphere_host`: Adds validation of the ESXI host thumbprint before adding the host to a cluster or vCenter Server.

### References

Closes #1549

### CODE REVIEW

File: vsphere/resource_vsphere_host.go [hunk 1]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
+	thumbprint := d.Get("thumbprint").(string)
+	hostname := d.Get("hostname").(string)
+	username := d.Get("username").(string)
+	password := d.Get("password").(string)
+
+	log.Printf("Building HostConnectSpec for host: %s", hostname)
+	// Retrieve the actual thumbprint from the host
+	actualThumbprint, err := getHostThumbprint(d)
+	if err != nil {
+		log.Printf("Error retrieving host thumbprint: %s", err)
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:849]:
```suggestion
```

File: vsphere/resource_vsphere_host.go [hunk 2]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
 
-func buildHostConnectSpec(d *schema.ResourceData) types.HostConnectSpec {
+func buildHostConnectSpec(d *schema.ResourceData) (types.HostConnectSpec, error) {
+	thumbprint := d.Get("thumbprint").(string)
+	hostname := d.Get("hostname").(string)
+	username := d.Get("username").(string)
+	password := d.Get("password").(string)
+
+	log.Printf("Building HostConnectSpec for host: %s", hostname)
+	// Retrieve the actual thumbprint from the host
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:846]:
```suggestion
	// Retrieve the actual thumbprint from the ESXi host.
```

File: vsphere/resource_vsphere_host.go [hunk 3]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
+	actualThumbprint, err := getHostThumbprint(d)
+	if err != nil {
+		log.Printf("Error retrieving host thumbprint: %s", err)
+		return types.HostConnectSpec{}, fmt.Errorf("error retrieving host thumbprint: %s", err)
+	}
+
+	// Compare the retrieved thumbprint with the provided thumbprint
+	if thumbprint != actualThumbprint {
+		log.Printf("Thumbprint mismatch: expected %s, got %s", thumbprint, actualThumbprint)
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:855]:
```suggestion
```

File: vsphere/resource_vsphere_host.go [hunk 4]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
+
+	log.Printf("Building HostConnectSpec for host: %s", hostname)
+	// Retrieve the actual thumbprint from the host
+	actualThumbprint, err := getHostThumbprint(d)
+	if err != nil {
+		log.Printf("Error retrieving host thumbprint: %s", err)
+		return types.HostConnectSpec{}, fmt.Errorf("error retrieving host thumbprint: %s", err)
+	}
+
+	// Compare the retrieved thumbprint with the provided thumbprint
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:853]:
```suggestion
	// Compare the the provided and returned thumbprints.
```

File: vsphere/resource_vsphere_host.go [hunk 5]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
+		}
+	}
+
+	config = &tls.Config{
+		InsecureSkipVerify: true,
+	}
+
+	conn, err := tls.Dial("tcp", address+":"+port, config)
+	if err != nil {
+		log.Printf("Error dialing TLS connection: %s", err)
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:894]:
```suggestion
```

File: vsphere/resource_vsphere_host.go [hunk 6]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
+	if p, ok := d.GetOk("port"); ok {
+		if portStr, ok := p.(string); ok {
+			port = portStr
+		} else {
+			return "", fmt.Errorf("port field is not a string")
+		}
+	}
+
+	config = &tls.Config{
+		InsecureSkipVerify: true,
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:889]: I think this should be based on `insecure_connection`.

File: vsphere/resource_vsphere_host.go [hunk 7]
```diff
@@ -826,15 +836,77 @@ func hostLockdownString(lockdownMode types.HostLockdownMode) (string, error) {
...
+func getHostThumbprint(d *schema.ResourceData) (string, error) {
+	config := &tls.Config{}
+
+	// Check and handle the "hostname" field
+	address, ok := d.Get("hostname").(string)
+	if !ok {
+		return "", fmt.Errorf("hostname field is not a string or is nil")
+	}
+
+	// Default port for HTTPS
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_host.go:878]:
```suggestion
	// Default port for HTTPS.
```

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Some small nits and question if we can get the `InsecureSkipVerify` based `insecure_connection` in the provider configuration.

File: vsphere/resource_vsphere_host.go (hunk 7 above)
Comment (burnsjared0415) [reply vsphere/resource_vsphere_host.go:878]: updated

File: vsphere/resource_vsphere_host.go (hunk 2 above)
Comment (burnsjared0415) [reply vsphere/resource_vsphere_host.go:846]: updated

File: vsphere/resource_vsphere_host.go (hunk 6 above)
Comment (burnsjared0415) [reply vsphere/resource_vsphere_host.go:889]: walk me through your thoughts on this

File: vsphere/resource_vsphere_host.go (hunk 4 above)
Comment (burnsjared0415) [reply vsphere/resource_vsphere_host.go:853]: updated

File: vsphere/resource_vsphere_host.go (hunk 6 above)
Comment (tenthirtyam) [reply vsphere/resource_vsphere_host.go:889]:
```suggestion
		InsecureSkipVerify: d.Get("insecure").(bool),
```

Comment (tenthirtyam) [reply vsphere/resource_vsphere_host.go:889]: The obove suggestion will set the value based on the provider configuration.

This is also done in `data_source_vsphere_host_thumbprint.go` but like this, which is also valid.

```go
	config := &tls.Config{}
	config.InsecureSkipVerify = d.Get("insecure").(bool)
```

Comment (burnsjared0415) [reply vsphere/resource_vsphere_host.go:889]: i thought that was the idea, i had to change the datasource and also the documentations to make insecure required

File: vsphere/resource_vsphere_host.go [hunk 8]
```diff
@@ -826,15 +836,77 @@
...
+	if p, ok := d.GetOk("port"); ok {
+		if portStr, ok := p.(string); ok {
+			port = portStr
+		} else {
+			return "", fmt.Errorf("port field is not a string")
+		}
+	}
+
+	config = &tls.Config{
+		InsecureSkipVerify: true,
```
[the remark this answers is not in the document]
Comment (burnsjared0415) [reply vsphere/resource_vsphere_host.go]: this is resolved now

**Review by tenthirtyam — APPROVED** [review]
LGTM!

**Comment by tenthirtyam** [comment]
Reset to draft.
