### PR TITLE
fix: add vm folder when querying for vm

### LINKED ISSUE #1524: Error: error while fetching the created vm, path '<VM-NAME>' resolves to multiple vms
### Terraform Version

v1.0.11

### vSphere Provider Version

v2.0.2

### vSphere Version

7.0.3.00100

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data vsphere_ovf_vm_template "n9k" {
  for_each = var.switches

  name             = "OVF_${each.key}"
  resource_pool_id = var.vsphere_rpool_id
  folder = var.vsphere_vmfolder_path
  datastore_id     =var.vsphere_ds_id
  host_system_id   = var.vsphere_host_id
  local_ovf_path = local.images[each.value.type]

  ip_protocol          = "IPV4"
  ip_allocation_policy = "STATIC_MANUAL"

  ovf_network_map = merge(
    { "Ethernet1_0" = var.vsphere_mgmt_lan_id, },
    { for k, v in each.value.nics : k => var.vsphere_networks[v].id if v !="" }
  )
}

resource vsphere_virtual_machine "n9k" {
  for_each = var.switches

  name = "${each.key}"
  annotation = each.value.type

  resource_pool_id = var.vsphere_rpool_id
  folder = var.vsphere_vmfolder_path

  datastore_id =var.vsphere_ds_id
  host_system_id = var.vsphere_host_id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout = 0
  datacenter_id = var.vsphere_dc_id

  num_cpus             = data.vsphere_ovf_vm_template.n9k[each.key].num_cpus
  num_cores_per_socket = data.vsphere_ovf_vm_template.n9k[each.key].num_cores_per_socket
  memory               = data.vsphere_ovf_vm_template.n9k[each.key].memory
  guest_id             = data.vsphere_ovf_vm_template.n9k[each.key].guest_id
  firmware = data.vsphere_ovf_vm_template.n9k[each.key].firmware

    dynamic "network_interface" {
      for_each = data.vsphere_ovf_vm_template.n9k[each.key].ovf_network_map
      content {
        network_id = network_interface.value
        adapter_type = "e1000"
      }
    }

  ovf_deploy {
    local_ovf_path = data.vsphere_ovf_vm_template.n9k[each.key].local_ovf_path
    disk_provisioning = "thin"

    ovf_network_map   = data.vsphere_ovf_vm_template.n9k[each.key].ovf_network_map
  }
}
```

### Debug Output

When running this with
* unique VM-Name [the _key_ of the map "var.switches"]
=> all runs just fine

When the VM-Name is not unique =>in the whole vCenter-Environment<=
=> it fails

but - the VM-Name ...
... it is unique within the VM-Folder and within the vSphere-Ressourcegroup

The whole Process of creating the VM from the OVF, the Network-Interface-Mapping, all is perfect.
=> the error message appears, when the VM-Deployment finishes

```DOS
c:\ terraform apply
...output omitted...
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Creating...
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Still creating... [10s elapsed]
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Still creating... [20s elapsed]
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Still creating... [30s elapsed]
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Still creating... [40s elapsed]
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Still creating... [50s elapsed]
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Still creating... [1m0s elapsed]
╷
│ Error: error while fetching the created vm, path 'SPINE-A' resolves to multiple vms
│
│   with module.n9k.vsphere_virtual_machine.n9k["SPINE-A"],
│   on ..\#modules\vsphere-n9k\20-nexus.tf line 40, in resource "vsphere_virtual_machine" "n9k":
│   40: resource vsphere_virtual_machine "n9k" {
│
╵
```
The error message points to line 40, which is:
```HCL
resource vsphere_virtual_machine "n9k" {
```
The error-message appears, before the message
```HCL
module.n9k.vsphere_virtual_machine.n9k["SPINE-A"]: Creation complete after 2m19s [id=42395476-4e72-13a3-014d-eaebd711998b]
```
could appear. (I did just rename the other "SPINE-A"-VM and rerun the whole setup, to double-check that the VM-Name is the root-cause... => Now everything was fine.)

=> the provider seems to want to do some additional customization and forgets to add the "-LOCATION" to the vSphere-API to retrieve the VM just created.
```HCL
var.vsphere_vmfolder_path
```
would contain "N9KV-VXLAN".

This is how PowerCLI would be able to distinguish between the other VM and the VM which has been just created:
```Powershell
PS C:\Users> $vm = get-VM -Name "LEAF-A"
PS C:\Users> $vm

Name                 PowerState Num CPUs MemoryGB
----                 ---------- -------- --------
LEAF-A               PoweredOff 4        8,000
LEAF-A               PoweredOn  4        8,000

PS C:\Users> $vm = get-VM -Name "LEAF-A" -Location "N9KV-VXLAN"
PS C:\Users> $vm

Name                 PowerState Num CPUs MemoryGB
----                 ---------- -------- --------
LEAF-A               PoweredOff 4        8,000

PS C:\Users> $vm = get-VM -Name "LEAF-A" -Location "N9KV"
PS C:\Users> $vm

Name                 PowerState Num CPUs MemoryGB
----                 ---------- -------- --------
LEAF-A               PoweredOn  4        8,000
```

### Expected Behavior

Terraform recognizes the VM-Location to identify the created object.

### Actual Behavior

Terraform ignores the VM-Location and relies on the user creating VMs with unique VM-Name.

It detects the hassle and stops the execution of the script.

### Steps to Reproduce

Create an empty VM with Name "X"
run a terraform-script to create a VM with Name "X" to a differend VM-Folder&Ressource-Group.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### PR DESCRIPTION
**Pull request by vasilsatanasov**
### Description

- Added the VM folder in the search for VMs criteria in deploy from OVF scenario.
- Added an e2e test. Verified that when the VM folder is not strictly specified the OVF deploy is passing. The query is in the default VM folder.

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```console
$ make testacc TESTARGS='-run=TestAccXXX'

API server listening at: 127.0.0.1:65413
=== RUN   TestAccResourceVSphereVirtualMachine_deployOvfFromUrlMultipleVmsSameName
--- PASS: TestAccResourceVSphereVirtualMachine_deployOvfFromUrlMultipleVmsSameName (162.90s)
PASS

Debugger finished with the exit code 0
```

### Release Note

```marrkdown
`r/virtual_machine`: Added the virtual machine folder in the search for virtual machine criteria when deploying from an OVF/OVA. scenario. Allows virtaul machines with same names in different virtual machine folders to be not distinguished as different managed entities. [GH 2118](https://github.com/hashicorp/terraform-provider-vsphere/pull/2118)
```

### References

Closes #1524

### CODE REVIEW

File: vsphere/resource_vsphere_virtual_machine_test.go [hunk 1]
```diff
@@ -2659,6 +2686,25 @@ func testAccResourceVSphereVirtualMachineCheckExists(expected bool) resource.Tes
...
+			missingState, _ := regexp.MatchString("not found in state", err.Error())
+			missingVSphere, _ := regexp.MatchString("virtual machine with UUID \"[-a-f0-9]+\" not found", err.Error())
+			if missingState && !expected || missingVSphere && !expected {
+				// Expected missing
+				return nil
+			}
+			return err
+		}
+		if !expected {
+			return errors.New("expected VM to be missing")
```
Comment (tenthirtyam) [inline vsphere/resource_vsphere_virtual_machine_test.go:2702]:
```suggestion
			return errors.New("expected vm to be missing")
```

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Minor text case change. Otherwise looks great!

**Review by tenthirtyam — APPROVED** [review]
LGTM
