### PR TITLE
Fix missing vapp properties

### LINKED ISSUE #1242: vApp properties not being set with OVF deployment with provider 1.24.1 and 1.24.2
### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "1.24.2"
    }
  }
}

variable "vsphere_user" {
  type = string
}

variable "vsphere_password" {
  type = string
}

variable "vsphere_server" {
  type = string
}

variable "vsphere_insecure" {
  type = bool
  default = true
}

variable "vsphere_datacenter" {
  type = string
}

variable "vsphere_datastore" {
  type = string
}

variable "vsphere_resource_pool" {
  type = string
}

variable "vsphere_host_system" {
  type = string
}

variable "vsphere_network" {
  type = string
}

variable "vsphere_ovf_url" {
  type = string
}

provider "vsphere" {
  user                  = var.vsphere_user
  password              = var.vsphere_password
  vsphere_server        = var.vsphere_server
  allow_unverified_ssl  = var.vsphere_insecure
}

data "vsphere_datacenter" "dc" {
  name = var.vsphere_datacenter
}

data "vsphere_resource_pool" "pool" {
  name          = var.vsphere_resource_pool
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_host" "host" {
  name          = var.vsphere_host_system
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "docker-hosts" {
  name             = "vsphere-provider-test01"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  datacenter_id    = data.vsphere_datacenter.dc.id
  host_system_id   = data.vsphere_host.host.id

  num_cpus = 4
  memory   = 4096
  guest_id = "other3xLinux64Guest"
  hv_mode  = "hvOff"

  disk {
    label = "disk0"
    size  = 20
  }

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  ovf_deploy {
    remote_ovf_url       = var.vsphere_ovf_url
    disk_provisioning    = "thin"
    ovf_network_map = {
      "nat" = data.vsphere_network.network.id
    }
  }

  vapp {
    properties = {
      "guestinfo.hostname" = "vsphere-provider-test01",
      "guestinfo.dns1" = "8.8.8.8",
      "guestinfo.dns2" = "8.8.4.4",
      "guestinfo.nic1.name" = "ens33",
      "guestinfo.nic1.ipaddress" = "192.168.0.10",
      "guestinfo.nic1.netmask" = "255.255.255.0",
      "guestinfo.nic1.gateway" = "192.168.0.1",
    }
  }
}

```

### Debug Output

https://gist.github.com/blakewade/b9874daed1732d27008558b7f09d034a

### Expected Behavior

The OVF is deployed and the values for the vApp properties are set

### Actual Behavior

No values for the vApp properties have been set

image

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is currently working for vSphere Provider 1.24.0

image

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by koikonom**
Due to the way maps behave in goland we ended up removing data from the
original map holding the vapp properties. The consequence was that if
expandVAppConfig was called more than once, we'd end up effectively
emptying the vapp properties map.

Fixes #1242.

### CODE REVIEW

**Review by aareet — APPROVED** [review]

File: vsphere/virtual_machine_config_structure.go [hunk 1]
```diff
@@ -5,6 +5,8 @@ import (
 	"log"
 	"reflect"
 
+	"github.com/mitchellh/copystructure"
```
Comment (aareet) [inline vsphere/virtual_machine_config_structure.go:8]: TIL!

**Review by aareet — APPROVED** [review]
